"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import fnmatch, os, glob 

matches = glob.glob('*.txt')
# for root, dirnames, filenames in os.walk('icons'):
# 	for filename in fnmatch.filter(filenames, '*.png'):
# 		matches.append((root, filename))

print matches
APP = ['FVR.py']
DATA_FILES = matches
OPTIONS = {'argv_emulation': True, 'iconfile': 'icons/fvr.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

## YOU have to add sendpraat, praat files and icons/ folder afterwards!!